# Numpy

#### Numpy provides:
   ##### 1.Extension packages to python for multidimensional arrays
   ##### 2.Closer to hardware efficiency
   ##### 3.Also known as array oriented programming
   ##### 4.Designed for Scientific computation

In [3]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


### Computation time using python lists

In [7]:
L=range(1000)
%timeit [i**2 for i in L]

212 µs ± 742 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a=np.arange(1000)
%timeit a**2

1.14 µs ± 8.54 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creating numpy arrays

## 1.1 Manual Construction of arrays

In [12]:
#1-D
import numpy as np
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [13]:
# dimensions
a.ndim

1

In [14]:
#shape
a.shape

(4,)

In [15]:
len(a)

4

In [17]:
#2-D & 3-D array
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
#dimension
a.ndim

2

In [19]:
#shape
a.shape

(2, 5)

In [20]:
len(a)

2

In [21]:
#3D Array
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
#dimension
c.ndim

3

In [24]:
c.shape

(2, 2, 2)

## Functions for creating arrays

In [27]:
a=np.arange(10)
a
#creates aan array between 0 and n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b=np.arange(1,45,2)
b
# the format is np.arnge(start,end,differnce)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43])

In [31]:
c=np.linspace(1,20,7)
c
# the format is np.linspace(start,end,no of points)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [32]:
np.ones((3,3))
#creating a matrix with row and column = i and j with every value 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.eye(5)
# creates an identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a=np.diag([1,2,3,4])
a
# creates a diagonal matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
#returns the diagonal element
np.diag(a)

array([1, 2, 3, 4])

In [45]:
#create a random numbers
a=np.random.rand(4)
a

array([0.71648395, 0.06527966, 0.57923019, 0.80523505])

In [46]:
np.random.randn(4)

array([-0.78712885, -0.0895684 , -0.7383089 ,  1.14957871])

## Basic Data Types

In [47]:
a=np.arange(10)
a.dtype

dtype('int64')

In [48]:
# data type can changed by this
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
#For zeros and ones the default datatype is float
b=np.ones(3)
b.dtype

dtype('float64')

#### other datatypes

In [54]:
#complex datatype
a=np.array([1+2j, 4+6j])
a.dtype

dtype('complex128')

In [55]:
b=np.array([True,False,True])
b.dtype
#boolean data type

dtype('bool')

In [59]:
c=np.array(['riju','rishav','arpita'])
c.dtype
#string data types

dtype('<U6')

## Indexing and Slicing

#### 3.1 Indexing

In [60]:
a=np.arange(10)
print(a[5])

5


In [61]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [62]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [63]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

#### 3.2 Slicing

In [65]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a[1:8:2]
#syntax is a[start_index:end_index:step]

array([1, 3, 5, 7])

In [67]:
a=np.arange(10)
a[5:]=10 #from element 5 change all to 10 
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [69]:
b=np.arange(5)
a[5:]=b[::-1]
b

array([0, 1, 2, 3, 4])

## Copies and Views

In [72]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [74]:
np.shares_memory(a,b)

True

In [75]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [76]:
a # a is modified because a and b are pointing to the same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [77]:
c=a[::2].copy()
c # forcing to make a copy and not sharing memory

array([10,  2,  4,  6,  8])

## Fancy Indexing

In [78]:
a=np.random.randint(10,20,15)
a

array([14, 16, 17, 18, 18, 10, 16, 17, 11, 14, 17, 12, 17, 15, 14])

In [79]:
mask=(a%2==0)

In [81]:
extracted_values=a[mask]
extracted_values
#performs the above operation which means a[mask] will diaplay no which are even

array([14, 16, 18, 18, 10, 16, 14, 12, 14])

In [83]:
a[mask]=-1
a
#all even  numbers become -1

array([-1, -1, 17, -1, -1, -1, -1, 17, 11, -1, 17, -1, 17, 15, -1])

In [84]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])